2020-07-14 16:28:56,108 ERROR: Exception on /user/andre [GET] [in /home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/andriy/my_projects/starnavi_jun/app/ui/main/routes.py", line 60, in user
    page, bp.config['POSTS_PER_PAGE'], False)
AttributeError: 'Blueprint' object has no attribute 'config'
2020-07-14 16:29:17,654 ERROR: Exception on /user/andre [GET] [in /home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/andriy/my_projects/starnavi_jun/app/ui/main/routes.py", line 60, in user
    page, current_app.config['POSTS_PER_PAGE'], False)
AttributeError: 'Blueprint' object has no attribute 'config'
2020-07-14 16:29:19,493 ERROR: Exception on /user/andre [GET] [in /home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/andriy/my_projects/starnavi_jun/app/ui/main/routes.py", line 60, in user
    page, current_app.config['POSTS_PER_PAGE'], False)
AttributeError: 'Blueprint' object has no attribute 'config'
2020-07-14 16:29:24,380 INFO: Starnavi [in /home/andriy/my_projects/starnavi_jun/app/__init__.py:59]
2020-07-14 16:29:30,169 ERROR: Exception on /user/andre [GET] [in /home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py:1758]
Traceback (most recent call last):
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/andriy/my_projects/starnavi_jun/app/ui/main/routes.py", line 66, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/andriy/my_projects/starnavi_jun/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/andriy/my_projects/starnavi_jun/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/andriy/my_projects/starnavi_jun/app/templates/user.html", line 36, in block "content"
    <a href="{{ url_for('like_action', post_id=post.id, action='unlike') }}">Unlike</a>
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/flask/helpers.py", line 344, in url_for
    rv = url_adapter.build(endpoint, values, method=method,
  File "/home/andriy/my_projects/starnavi_jun/venv/lib/python3.8/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'like_action' with values ['action', 'post_id']. Did you mean 'main.like_action' instead?
2020-07-14 16:30:32,168 INFO: Starnavi [in /home/andriy/my_projects/starnavi_jun/app/__init__.py:59]
2020-07-14 16:32:15,339 INFO: Starnavi [in /home/andriy/my_projects/starnavi_jun/app/__init__.py:59]
